# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import whisper_pb2 as whisper__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in whisper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WhisperServiceStub(object):
    """Whisper gRPC Service for transcription
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/whisper.WhisperService/Transcribe',
                request_serializer=whisper__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=whisper__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/whisper.WhisperService/GetJobStatus',
                request_serializer=whisper__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=whisper__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CreateUploadSession = channel.unary_unary(
                '/whisper.WhisperService/CreateUploadSession',
                request_serializer=whisper__pb2.CreateUploadSessionRequest.SerializeToString,
                response_deserializer=whisper__pb2.UploadSessionResponse.FromString,
                _registered_method=True)
        self.UploadChunk = channel.stream_unary(
                '/whisper.WhisperService/UploadChunk',
                request_serializer=whisper__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=whisper__pb2.UploadChunkResponse.FromString,
                _registered_method=True)
        self.GetUploadSessionStatus = channel.unary_unary(
                '/whisper.WhisperService/GetUploadSessionStatus',
                request_serializer=whisper__pb2.GetUploadSessionStatusRequest.SerializeToString,
                response_deserializer=whisper__pb2.UploadSessionResponse.FromString,
                _registered_method=True)
        self.FinalizeUploadSession = channel.unary_unary(
                '/whisper.WhisperService/FinalizeUploadSession',
                request_serializer=whisper__pb2.FinalizeUploadSessionRequest.SerializeToString,
                response_deserializer=whisper__pb2.FinalizeUploadSessionResponse.FromString,
                _registered_method=True)


class WhisperServiceServicer(object):
    """Whisper gRPC Service for transcription
    """

    def Transcribe(self, request, context):
        """Transcribe audio file (synchronous)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get transcription job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUploadSession(self, request, context):
        """Create upload session for chunked upload
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadChunk(self, request_iterator, context):
        """Upload audio chunk (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadSessionStatus(self, request, context):
        """Get upload session status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeUploadSession(self, request, context):
        """Finalize upload session and get merged file path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhisperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=whisper__pb2.TranscribeRequest.FromString,
                    response_serializer=whisper__pb2.TranscribeResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=whisper__pb2.GetJobStatusRequest.FromString,
                    response_serializer=whisper__pb2.JobStatusResponse.SerializeToString,
            ),
            'CreateUploadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUploadSession,
                    request_deserializer=whisper__pb2.CreateUploadSessionRequest.FromString,
                    response_serializer=whisper__pb2.UploadSessionResponse.SerializeToString,
            ),
            'UploadChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadChunk,
                    request_deserializer=whisper__pb2.UploadChunkRequest.FromString,
                    response_serializer=whisper__pb2.UploadChunkResponse.SerializeToString,
            ),
            'GetUploadSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadSessionStatus,
                    request_deserializer=whisper__pb2.GetUploadSessionStatusRequest.FromString,
                    response_serializer=whisper__pb2.UploadSessionResponse.SerializeToString,
            ),
            'FinalizeUploadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeUploadSession,
                    request_deserializer=whisper__pb2.FinalizeUploadSessionRequest.FromString,
                    response_serializer=whisper__pb2.FinalizeUploadSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whisper.WhisperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whisper.WhisperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WhisperService(object):
    """Whisper gRPC Service for transcription
    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper.WhisperService/Transcribe',
            whisper__pb2.TranscribeRequest.SerializeToString,
            whisper__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper.WhisperService/GetJobStatus',
            whisper__pb2.GetJobStatusRequest.SerializeToString,
            whisper__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUploadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper.WhisperService/CreateUploadSession',
            whisper__pb2.CreateUploadSessionRequest.SerializeToString,
            whisper__pb2.UploadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/whisper.WhisperService/UploadChunk',
            whisper__pb2.UploadChunkRequest.SerializeToString,
            whisper__pb2.UploadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploadSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper.WhisperService/GetUploadSessionStatus',
            whisper__pb2.GetUploadSessionStatusRequest.SerializeToString,
            whisper__pb2.UploadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeUploadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whisper.WhisperService/FinalizeUploadSession',
            whisper__pb2.FinalizeUploadSessionRequest.SerializeToString,
            whisper__pb2.FinalizeUploadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
