// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cache/flush": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove all data from the cache storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "07. Flush"
                ],
                "summary": "Flush all cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag/control": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Queue a RAG task to process natural language command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Control devices via natural language",
                "parameters": [
                    {
                        "description": "RAG Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RAGRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag/summary": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transform a long transcription into professional meeting minutes. Supports target language (id/en), context, and style selection.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Generate meeting minutes summary",
                "parameters": [
                    {
                        "description": "Summary request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RAGSummaryRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.RAGSummaryResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag/translate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Translate text to English using the LLM. Best for short phrases/commands.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Translate text to English",
                "parameters": [
                    {
                        "description": "Translation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RAGRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag/{task_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Get RAG task status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.RAGStatusDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/recordings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a paginated list of recordings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "06. Recordings"
                ],
                "summary": "Get all recordings",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.GetAllRecordingsResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload an audio file and save its metadata",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "06. Recordings"
                ],
                "summary": "Upload a recording",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    }
                }
            }
        },
        "/api/recordings/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a single recording's metadata by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "06. Recordings"
                ],
                "summary": "Get a recording by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recording ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingResponseDto"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Hard delete a recording's metadata and its physical file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "06. Recordings"
                ],
                "summary": "Delete a recording",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recording ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.RecordingStandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start transcription of audio file using local Whisper STT. Asynchronous processing. Supports: .mp3, .wav, .m4a, .aac, .ogg, .flac.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe audio file (Whisper)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TranscriptionTaskResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/ppu": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit audio file for transcription via Outsystems proxy. Processing is asynchronous.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe audio file (Proxy to Outsystems)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TranscriptionTaskResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/whisper/cpp": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start transcription of audio file using Whisper.cpp. Asynchronous processing with background execution. Pure Whisper.cpp, no PPU. Supports: .mp3, .wav, .m4a, .aac, .ogg, .flac.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe audio file (Whisper.cpp)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Language code (e.g. id, en)",
                        "name": "language",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TranscriptionTaskResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/{transcribe_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the status and result of any transcription task (Short, Long, or PPU).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Get transcription status (Consolidated)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "transcribe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.AsyncTranscriptionProcessStatusResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/teralux/{id}/scenes": {
            "get": {
                "description": "Retrieve a list of all configured scenes for a specific Teralux device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "List all scenes for a Teralux device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teralux UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of scenes",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dtos.SceneListResponseDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Create a scene with a name and a list of actions (Tuya/MQTT)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Create a new scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teralux UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Scene configuration",
                        "name": "scene",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateSceneRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Scene created",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/teralux/{id}/scenes/{scene_id}": {
            "put": {
                "description": "Update the configuration of a specific scene",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Update an existing scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teralux UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "scene_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated scene configuration",
                        "name": "scene",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateSceneRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene updated",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Scene not found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a specific scene configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Delete a scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teralux UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "scene_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene deleted",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/teralux/{id}/scenes/{scene_id}/control": {
            "get": {
                "description": "Trigger all actions defined in a specific scene",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Apply/Trigger a scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Teralux UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "scene_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene applied",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/auth": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Authenticates the user and retrieves a Tuya access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "01. Auth"
                ],
                "summary": "Authenticate with Tuya",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaAuthResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all devices in a Merged View (Smart IR remotes merged with Hubs). Sorted alphabetically by Name. For infrared_ac devices, the status array is populated with saved device state (power, temp, mode, wind) or default values if no state exists.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get All Devices",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (alias for limit)",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaDevicesResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/sync": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches real-time status from Tuya. Does NOT update local DB. Returns fresh device list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Sync Teralux Device Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dtos.TuyaSyncDeviceDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves details of a specific device by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get Device by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaDeviceResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/commands/ir": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends an infrared command to an AC via a specific IR device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Send IR AC Command",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Infrared Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "IR AC Command Payload",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.TuyaIRACCommandDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/commands/switch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a command to a specific Tuya device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Send Command to Device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Command Payload",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.TuyaCommandDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/sensor": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves sensor data (temperature, humidity, etc.) for a specific device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get Sensor Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.SensorDataDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the application and database are healthy",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "08. Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ActionDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.AsyncTranscriptionProcessStatusResponseDTO": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                },
                "task_status": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionStatusDTO"
                }
            }
        },
        "dtos.AsyncTranscriptionResultDTO": {
            "type": "object",
            "properties": {
                "detected_language": {
                    "type": "string",
                    "example": "id"
                },
                "refined_text": {
                    "type": "string",
                    "example": "Hello world"
                },
                "transcription": {
                    "type": "string",
                    "example": "Halo dunia"
                }
            }
        },
        "dtos.AsyncTranscriptionStatusDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionResultDTO"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "dtos.CreateSceneRequestDTO": {
            "type": "object",
            "required": [
                "name",
                "teralux_id"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ActionDTO"
                    }
                },
                "name": {
                    "type": "string"
                },
                "teralux_id": {
                    "type": "string"
                }
            }
        },
        "dtos.GetAllRecordingsResponseDto": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "recordings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.RecordingResponseDto"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.RAGRequestDTO": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "dtos.RAGStatusDTO": {
            "type": "object",
            "properties": {
                "body": {},
                "endpoint": {
                    "type": "string"
                },
                "execution_result": {
                    "description": "holds the response from the fetched endpoint"
                },
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "result": {
                    "description": "raw LLM response when not structured",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.RAGSummaryRequestDTO": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "context": {
                    "type": "string",
                    "example": "technical meeting"
                },
                "language": {
                    "description": "\"id\" or \"en\"",
                    "type": "string",
                    "example": "id"
                },
                "style": {
                    "type": "string",
                    "example": "professional"
                },
                "text": {
                    "type": "string",
                    "example": "This is a long transcript of a technical meeting..."
                }
            }
        },
        "dtos.RAGSummaryResponseDTO": {
            "type": "object",
            "properties": {
                "pdf_url": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "dtos.RecordingResponseDto": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                }
            }
        },
        "dtos.RecordingStandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "dtos.SceneListResponseDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "teralux_id": {
                    "type": "string"
                }
            }
        },
        "dtos.SensorDataDTO": {
            "type": "object",
            "properties": {
                "battery_percentage": {
                    "type": "integer"
                },
                "humidity": {
                    "type": "integer"
                },
                "status_text": {
                    "type": "string"
                },
                "temp_unit": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "dtos.TranscriptionTaskResponseDTO": {
            "type": "object",
            "properties": {
                "recording_id": {
                    "type": "string",
                    "example": "uuid-v4"
                },
                "task_id": {
                    "type": "string",
                    "example": "abc-123"
                },
                "task_status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "dtos.TuyaAuthResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expire_time": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "dtos.TuyaCommandDTO": {
            "type": "object",
            "required": [
                "code",
                "value"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.TuyaDeviceDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                    }
                },
                "create_time": {
                    "type": "integer"
                },
                "custom_name": {
                    "type": "string"
                },
                "gateway_id": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "local_key": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "product_name": {
                    "type": "string"
                },
                "remote_category": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "remote_product_name": {
                    "type": "string"
                },
                "status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceStatusDTO"
                    }
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaDeviceResponseDTO": {
            "type": "object",
            "properties": {
                "device": {
                    "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                }
            }
        },
        "dtos.TuyaDeviceStatusDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.TuyaDevicesResponseDTO": {
            "type": "object",
            "properties": {
                "current_page_count": {
                    "type": "integer"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_devices": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaIRACCommandDTO": {
            "type": "object",
            "required": [
                "code",
                "remote_id"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaSyncDeviceDTO": {
            "type": "object",
            "properties": {
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "remote_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dtos.UpdateSceneRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ActionDTO"
                    }
                },
                "name": {
                    "type": "string"
                },
                "teralux_id": {
                    "type": "string"
                }
            }
        },
        "teralux_app_domain_common_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "teralux_app_domain_rag_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "teralux_app_domain_speech_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        },
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Authentication endpoints",
            "name": "01. Auth"
        },
        {
            "description": "Tuya related endpoints",
            "name": "02. Tuya"
        },
        {
            "description": "Scene management and control endpoints",
            "name": "03. Scenes"
        },
        {
            "description": "Speech endpoints",
            "name": "04. Speech"
        },
        {
            "description": "RAG endpoints",
            "name": "05. RAG"
        },
        {
            "description": "Recordings management endpoints",
            "name": "06. Recordings"
        },
        {
            "description": "Cache management endpoints",
            "name": "07. Flush"
        },
        {
            "description": "Health check endpoint",
            "name": "08. Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Teralux API",
	Description:      "This is the API server for Teralux App. <br> For full documentation, visit <a href=\"/docs\">/docs</a>.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
