// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cache/flush": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove all data from the cache storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "06. Flush"
                ],
                "summary": "Flush all cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit text for RAG processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Process text via RAG",
                "parameters": [
                    {
                        "description": "RAG request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RAGRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.RAGProcessResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/rag/{task_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "05. RAG"
                ],
                "summary": "Get RAG task status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.RAGStatusDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_rag_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/scenes": {
            "get": {
                "description": "Retrieve a list of all configured scenes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "List all scenes",
                "responses": {
                    "200": {
                        "description": "List of scenes",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dtos.SceneListResponseDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Create a scene with a name and a list of actions (Tuya/MQTT)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Create a new scene",
                "parameters": [
                    {
                        "description": "Scene configuration",
                        "name": "scene",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateSceneRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Scene created",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/scenes/{id}": {
            "put": {
                "description": "Update the configuration of a specific scene",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Update an existing scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated scene configuration",
                        "name": "scene",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateSceneRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene updated",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Scene not found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a specific scene configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Delete a scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene deleted",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/scenes/{id}/control": {
            "get": {
                "description": "Trigger all actions defined in a specific scene",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "03. Scenes"
                ],
                "summary": "Apply/Trigger a scene",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scene UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Scene applied",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/mqtt/publish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Publish a message to the configured MQTT topic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Publish message to MQTT",
                "parameters": [
                    {
                        "description": "Message to publish",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.MqttPublishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start transcription of audio file. Attempts PPU (Outsystems) first, falls back to local Whisper if PPU fails. Asynchronous processing. Supports: .mp3, .wav, .m4a, .aac, .ogg, .flac.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe audio file (with PPU fallback)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.AsyncTranscriptionProcessResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/long": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start transcription of long audio file using Whisper. Asynchronous processing with background execution. No translation, no RAG. Supports: .mp3, .wav, .m4a, .aac, .ogg, .flac.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe long audio file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Language code (e.g. id, en)",
                        "name": "language",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.AsyncTranscriptionLongProcessResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/ppu": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit audio file for transcription via Outsystems proxy. Processing is asynchronous.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Transcribe audio file (Proxy to Outsystems)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Audio file (.mp3, .wav, .m4a, .aac, .ogg, .flac)",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.WhisperProxyProcessResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/speech/transcribe/{transcribe_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the status and result of any transcription task (Short, Long, or PPU).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "04. Speech"
                ],
                "summary": "Get transcription status (Consolidated)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "transcribe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.AsyncTranscriptionProcessResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_speech_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/auth": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Authenticates the user and retrieves a Tuya access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "01. Auth"
                ],
                "summary": "Authenticate with Tuya",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaAuthResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all devices in a Merged View (Smart IR remotes merged with Hubs). Sorted alphabetically by Name. For infrared_ac devices, the status array is populated with saved device state (power, temp, mode, wind) or default values if no state exists.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get All Devices",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (alias for limit)",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaDevicesResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/sync": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches real-time status from Tuya. Does NOT update local DB. Returns fresh device list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Sync Teralux Device Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dtos.TuyaSyncDeviceDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves details of a specific device by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get Device by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.TuyaDeviceResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/commands/ir": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends an infrared command to an AC via a specific IR device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Send IR AC Command",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Infrared Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "IR AC Command Payload",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.TuyaIRACCommandDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/commands/switch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a command to a specific Tuya device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Send Command to Device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Command Payload",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.TuyaCommandDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/tuya/devices/{id}/sensor": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves sensor data (temperature, humidity, etc.) for a specific device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "02. Tuya"
                ],
                "summary": "Get Sensor Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtos.SensorDataDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teralux_app_domain_common_dtos.StandardResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the application and database are healthy",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "07. Health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ActionDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.AsyncTranscriptionLongProcessResponseDTO": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                },
                "task_status": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionLongStatusDTO"
                }
            }
        },
        "dtos.AsyncTranscriptionLongResultDTO": {
            "type": "object",
            "properties": {
                "detected_language": {
                    "type": "string",
                    "example": "id"
                },
                "text": {
                    "type": "string",
                    "example": "Ini adalah transkripsi yang sangat panjang..."
                }
            }
        },
        "dtos.AsyncTranscriptionLongStatusDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionLongResultDTO"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "dtos.AsyncTranscriptionProcessResponseDTO": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                },
                "task_status": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionStatusDTO"
                }
            }
        },
        "dtos.AsyncTranscriptionResultDTO": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "example": "Halo dunia"
                },
                "translated_text": {
                    "type": "string",
                    "example": "Hello world"
                }
            }
        },
        "dtos.AsyncTranscriptionStatusDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/dtos.AsyncTranscriptionResultDTO"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "dtos.CreateSceneRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ActionDTO"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.MqttPublishRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.OutsystemsTranscriptionResultDTO": {
            "type": "object",
            "properties": {
                "detected_language": {
                    "type": "string",
                    "example": "id"
                },
                "filename": {
                    "type": "string",
                    "example": "audio.mp3"
                },
                "transcription": {
                    "type": "string",
                    "example": "Halo dunia"
                }
            }
        },
        "dtos.RAGProcessResponseDTO": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                },
                "task_status": {
                    "$ref": "#/definitions/dtos.RAGStatusDTO"
                }
            }
        },
        "dtos.RAGRequestDTO": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "dtos.RAGStatusDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "result": {
                    "description": "raw LLM response when not structured",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.SceneListResponseDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.SensorDataDTO": {
            "type": "object",
            "properties": {
                "battery_percentage": {
                    "type": "integer"
                },
                "humidity": {
                    "type": "integer"
                },
                "status_text": {
                    "type": "string"
                },
                "temp_unit": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "dtos.TuyaAuthResponseDTO": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expire_time": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "dtos.TuyaCommandDTO": {
            "type": "object",
            "required": [
                "code",
                "value"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.TuyaDeviceDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                    }
                },
                "create_time": {
                    "type": "integer"
                },
                "custom_name": {
                    "type": "string"
                },
                "gateway_id": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "local_key": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "product_name": {
                    "type": "string"
                },
                "remote_category": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "remote_product_name": {
                    "type": "string"
                },
                "status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceStatusDTO"
                    }
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaDeviceResponseDTO": {
            "type": "object",
            "properties": {
                "device": {
                    "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                }
            }
        },
        "dtos.TuyaDeviceStatusDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "dtos.TuyaDevicesResponseDTO": {
            "type": "object",
            "properties": {
                "current_page_count": {
                    "type": "integer"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TuyaDeviceDTO"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_devices": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaIRACCommandDTO": {
            "type": "object",
            "required": [
                "code",
                "remote_id"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "remote_id": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dtos.TuyaSyncDeviceDTO": {
            "type": "object",
            "properties": {
                "create_time": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "remote_id": {
                    "type": "string"
                },
                "update_time": {
                    "type": "integer"
                }
            }
        },
        "dtos.UpdateSceneRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ActionDTO"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.WhisperProxyProcessResponseDTO": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                },
                "task_status": {
                    "$ref": "#/definitions/dtos.WhisperProxyStatusDTO"
                }
            }
        },
        "dtos.WhisperProxyStatusDTO": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "result": {
                    "$ref": "#/definitions/dtos.OutsystemsTranscriptionResultDTO"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                }
            }
        },
        "teralux_app_domain_common_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "teralux_app_domain_rag_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "teralux_app_domain_speech_dtos.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        },
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Authentication endpoints",
            "name": "01. Auth"
        },
        {
            "description": "Tuya related endpoints",
            "name": "02. Tuya"
        },
        {
            "description": "Scene management and control endpoints",
            "name": "03. Scenes"
        },
        {
            "description": "Speech endpoints",
            "name": "04. Speech"
        },
        {
            "description": "RAG endpoints",
            "name": "05. RAG"
        },
        {
            "description": "Cache management endpoints",
            "name": "06. Flush"
        },
        {
            "description": "Health check endpoint",
            "name": "07. Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Teralux API",
	Description:      "This is the API server for Teralux App. <br> For full documentation, visit <a href=\"/docs\">/docs</a>.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
