// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: whisper.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhisperService_Transcribe_FullMethodName             = "/whisper.WhisperService/Transcribe"
	WhisperService_GetJobStatus_FullMethodName           = "/whisper.WhisperService/GetJobStatus"
	WhisperService_CreateUploadSession_FullMethodName    = "/whisper.WhisperService/CreateUploadSession"
	WhisperService_UploadChunk_FullMethodName            = "/whisper.WhisperService/UploadChunk"
	WhisperService_GetUploadSessionStatus_FullMethodName = "/whisper.WhisperService/GetUploadSessionStatus"
	WhisperService_FinalizeUploadSession_FullMethodName  = "/whisper.WhisperService/FinalizeUploadSession"
)

// WhisperServiceClient is the client API for WhisperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Whisper gRPC Service for transcription
type WhisperServiceClient interface {
	// Transcribe audio file (synchronous)
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	// Get transcription job status
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	// Create upload session for chunked upload
	CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*UploadSessionResponse, error)
	// Upload audio chunk (streaming)
	UploadChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunkRequest, UploadChunkResponse], error)
	// Get upload session status
	GetUploadSessionStatus(ctx context.Context, in *GetUploadSessionStatusRequest, opts ...grpc.CallOption) (*UploadSessionResponse, error)
	// Finalize upload session and get merged file path
	FinalizeUploadSession(ctx context.Context, in *FinalizeUploadSessionRequest, opts ...grpc.CallOption) (*FinalizeUploadSessionResponse, error)
}

type whisperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhisperServiceClient(cc grpc.ClientConnInterface) WhisperServiceClient {
	return &whisperServiceClient{cc}
}

func (c *whisperServiceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, WhisperService_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whisperServiceClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, WhisperService_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whisperServiceClient) CreateUploadSession(ctx context.Context, in *CreateUploadSessionRequest, opts ...grpc.CallOption) (*UploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSessionResponse)
	err := c.cc.Invoke(ctx, WhisperService_CreateUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whisperServiceClient) UploadChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunkRequest, UploadChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WhisperService_ServiceDesc.Streams[0], WhisperService_UploadChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunkRequest, UploadChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhisperService_UploadChunkClient = grpc.ClientStreamingClient[UploadChunkRequest, UploadChunkResponse]

func (c *whisperServiceClient) GetUploadSessionStatus(ctx context.Context, in *GetUploadSessionStatusRequest, opts ...grpc.CallOption) (*UploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSessionResponse)
	err := c.cc.Invoke(ctx, WhisperService_GetUploadSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whisperServiceClient) FinalizeUploadSession(ctx context.Context, in *FinalizeUploadSessionRequest, opts ...grpc.CallOption) (*FinalizeUploadSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeUploadSessionResponse)
	err := c.cc.Invoke(ctx, WhisperService_FinalizeUploadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhisperServiceServer is the server API for WhisperService service.
// All implementations must embed UnimplementedWhisperServiceServer
// for forward compatibility.
//
// Whisper gRPC Service for transcription
type WhisperServiceServer interface {
	// Transcribe audio file (synchronous)
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	// Get transcription job status
	GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error)
	// Create upload session for chunked upload
	CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*UploadSessionResponse, error)
	// Upload audio chunk (streaming)
	UploadChunk(grpc.ClientStreamingServer[UploadChunkRequest, UploadChunkResponse]) error
	// Get upload session status
	GetUploadSessionStatus(context.Context, *GetUploadSessionStatusRequest) (*UploadSessionResponse, error)
	// Finalize upload session and get merged file path
	FinalizeUploadSession(context.Context, *FinalizeUploadSessionRequest) (*FinalizeUploadSessionResponse, error)
	mustEmbedUnimplementedWhisperServiceServer()
}

// UnimplementedWhisperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhisperServiceServer struct{}

func (UnimplementedWhisperServiceServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedWhisperServiceServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedWhisperServiceServer) CreateUploadSession(context.Context, *CreateUploadSessionRequest) (*UploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUploadSession not implemented")
}
func (UnimplementedWhisperServiceServer) UploadChunk(grpc.ClientStreamingServer[UploadChunkRequest, UploadChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadChunk not implemented")
}
func (UnimplementedWhisperServiceServer) GetUploadSessionStatus(context.Context, *GetUploadSessionStatusRequest) (*UploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadSessionStatus not implemented")
}
func (UnimplementedWhisperServiceServer) FinalizeUploadSession(context.Context, *FinalizeUploadSessionRequest) (*FinalizeUploadSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeUploadSession not implemented")
}
func (UnimplementedWhisperServiceServer) mustEmbedUnimplementedWhisperServiceServer() {}
func (UnimplementedWhisperServiceServer) testEmbeddedByValue()                        {}

// UnsafeWhisperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhisperServiceServer will
// result in compilation errors.
type UnsafeWhisperServiceServer interface {
	mustEmbedUnimplementedWhisperServiceServer()
}

func RegisterWhisperServiceServer(s grpc.ServiceRegistrar, srv WhisperServiceServer) {
	// If the following call panics, it indicates UnimplementedWhisperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhisperService_ServiceDesc, srv)
}

func _WhisperService_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServiceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhisperService_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServiceServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhisperService_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServiceServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhisperService_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServiceServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhisperService_CreateUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServiceServer).CreateUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhisperService_CreateUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServiceServer).CreateUploadSession(ctx, req.(*CreateUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhisperService_UploadChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WhisperServiceServer).UploadChunk(&grpc.GenericServerStream[UploadChunkRequest, UploadChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhisperService_UploadChunkServer = grpc.ClientStreamingServer[UploadChunkRequest, UploadChunkResponse]

func _WhisperService_GetUploadSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServiceServer).GetUploadSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhisperService_GetUploadSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServiceServer).GetUploadSessionStatus(ctx, req.(*GetUploadSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhisperService_FinalizeUploadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeUploadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServiceServer).FinalizeUploadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhisperService_FinalizeUploadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServiceServer).FinalizeUploadSession(ctx, req.(*FinalizeUploadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhisperService_ServiceDesc is the grpc.ServiceDesc for WhisperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhisperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whisper.WhisperService",
	HandlerType: (*WhisperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _WhisperService_Transcribe_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _WhisperService_GetJobStatus_Handler,
		},
		{
			MethodName: "CreateUploadSession",
			Handler:    _WhisperService_CreateUploadSession_Handler,
		},
		{
			MethodName: "GetUploadSessionStatus",
			Handler:    _WhisperService_GetUploadSessionStatus_Handler,
		},
		{
			MethodName: "FinalizeUploadSession",
			Handler:    _WhisperService_FinalizeUploadSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadChunk",
			Handler:       _WhisperService_UploadChunk_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "whisper.proto",
}
