// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: whisper.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`             // Audio file content
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                // Original file name
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                                // Language code (e.g., "id", "en")
	Diarize       bool                   `protobuf:"varint,4,opt,name=diarize,proto3" json:"diarize,omitempty"`                                 // Enable speaker diarization
	ModelId       string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                   // Optional model ID
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Request tracking ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_whisper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TranscribeRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TranscribeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeRequest) GetDiarize() bool {
	if x != nil {
		return x.Diarize
	}
	return false
}

func (x *TranscribeRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TranscribeRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`              // Task/Job ID for polling
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                            // "pending", "processing", "completed", "failed"
	Transcript    string                 `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"`                    // Transcription result (if completed)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                              // Error message (if failed)
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Processing duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_whisper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TranscribeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TranscribeResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *TranscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TranscribeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                         // Job/Task ID
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Request tracking ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_whisper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                         // "processing", "completed", "failed"
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                         // Transcription text (if completed)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                           // Error message (if failed)
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`     // Original file name
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_whisper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *JobStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobStatusResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *JobStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                // Original file name
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`            // Total file size in bytes
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`         // Number of chunks
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Request tracking ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_whisper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUploadSessionRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *CreateUploadSessionRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *CreateUploadSessionRequest) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *CreateUploadSessionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type UploadSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	TotalSize      int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ChunkCount     int32                  `protobuf:"varint,4,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	UploadedChunks int32                  `protobuf:"varint,5,opt,name=uploaded_chunks,json=uploadedChunks,proto3" json:"uploaded_chunks,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                         // "uploading", "ready", "consumed", "expired"
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	ExpiresAt      int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadSessionResponse) Reset() {
	*x = UploadSessionResponse{}
	mi := &file_whisper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSessionResponse) ProtoMessage() {}

func (x *UploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSessionResponse.ProtoReflect.Descriptor instead.
func (*UploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{5}
}

func (x *UploadSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadSessionResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadSessionResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadSessionResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *UploadSessionResponse) GetUploadedChunks() int32 {
	if x != nil {
		return x.UploadedChunks
	}
	return 0
}

func (x *UploadSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadSessionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UploadSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UploadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunkRequest) Reset() {
	*x = UploadChunkRequest{}
	mi := &file_whisper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkRequest) ProtoMessage() {}

func (x *UploadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkRequest.ProtoReflect.Descriptor instead.
func (*UploadChunkRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{6}
}

func (x *UploadChunkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *UploadChunkRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type UploadChunkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkIndex     int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	UploadedChunks int32                  `protobuf:"varint,5,opt,name=uploaded_chunks,json=uploadedChunks,proto3" json:"uploaded_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadChunkResponse) Reset() {
	*x = UploadChunkResponse{}
	mi := &file_whisper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunkResponse) ProtoMessage() {}

func (x *UploadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunkResponse.ProtoReflect.Descriptor instead.
func (*UploadChunkResponse) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{7}
}

func (x *UploadChunkResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadChunkResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadChunkResponse) GetUploadedChunks() int32 {
	if x != nil {
		return x.UploadedChunks
	}
	return 0
}

type GetUploadSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadSessionStatusRequest) Reset() {
	*x = GetUploadSessionStatusRequest{}
	mi := &file_whisper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionStatusRequest) ProtoMessage() {}

func (x *GetUploadSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUploadSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{8}
}

func (x *GetUploadSessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUploadSessionStatusRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type FinalizeUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadSessionRequest) Reset() {
	*x = FinalizeUploadSessionRequest{}
	mi := &file_whisper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadSessionRequest) ProtoMessage() {}

func (x *FinalizeUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*FinalizeUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeUploadSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinalizeUploadSessionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type FinalizeUploadSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MergedFilePath string                 `protobuf:"bytes,2,opt,name=merged_file_path,json=mergedFilePath,proto3" json:"merged_file_path,omitempty"` // Path to merged audio file
	FileName       string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	TotalSize      int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Success        bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinalizeUploadSessionResponse) Reset() {
	*x = FinalizeUploadSessionResponse{}
	mi := &file_whisper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadSessionResponse) ProtoMessage() {}

func (x *FinalizeUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whisper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*FinalizeUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_whisper_proto_rawDescGZIP(), []int{10}
}

func (x *FinalizeUploadSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinalizeUploadSessionResponse) GetMergedFilePath() string {
	if x != nil {
		return x.MergedFilePath
	}
	return ""
}

func (x *FinalizeUploadSessionResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FinalizeUploadSessionResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FinalizeUploadSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinalizeUploadSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_whisper_proto protoreflect.FileDescriptor

const file_whisper_proto_rawDesc = "" +
	"\n" +
	"\rwhisper.proto\x12\awhisper\"\xc7\x01\n" +
	"\x11TranscribeRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\adiarize\x18\x04 \x01(\bR\adiarize\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\"\x9c\x01\n" +
	"\x12TranscribeResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"transcript\x18\x03 \x01(\tR\n" +
	"transcript\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"S\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"\xcb\x01\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa0\x01\n" +
	"\x1aCreateUploadSessionRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\x92\x02\n" +
	"\x15UploadSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vchunk_count\x18\x04 \x01(\x05R\n" +
	"chunkCount\x12'\n" +
	"\x0fuploaded_chunks\x18\x05 \x01(\x05R\x0euploadedChunks\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\"\x9a\x01\n" +
	"\x12UploadChunkRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xae\x01\n" +
	"\x13UploadChunkResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12'\n" +
	"\x0fuploaded_chunks\x18\x05 \x01(\x05R\x0euploadedChunks\"e\n" +
	"\x1dGetUploadSessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"d\n" +
	"\x1cFinalizeUploadSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"\xd4\x01\n" +
	"\x1dFinalizeUploadSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\x10merged_file_path\x18\x02 \x01(\tR\x0emergedFilePath\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\x93\x04\n" +
	"\x0eWhisperService\x12E\n" +
	"\n" +
	"Transcribe\x12\x1a.whisper.TranscribeRequest\x1a\x1b.whisper.TranscribeResponse\x12H\n" +
	"\fGetJobStatus\x12\x1c.whisper.GetJobStatusRequest\x1a\x1a.whisper.JobStatusResponse\x12Z\n" +
	"\x13CreateUploadSession\x12#.whisper.CreateUploadSessionRequest\x1a\x1e.whisper.UploadSessionResponse\x12J\n" +
	"\vUploadChunk\x12\x1b.whisper.UploadChunkRequest\x1a\x1c.whisper.UploadChunkResponse(\x01\x12`\n" +
	"\x16GetUploadSessionStatus\x12&.whisper.GetUploadSessionStatusRequest\x1a\x1e.whisper.UploadSessionResponse\x12f\n" +
	"\x15FinalizeUploadSession\x12%.whisper.FinalizeUploadSessionRequest\x1a&.whisper.FinalizeUploadSessionResponseB2Z-sensio/domain/models-v1/whisper/services/grpc\x90\x01\x01b\x06proto3"

var (
	file_whisper_proto_rawDescOnce sync.Once
	file_whisper_proto_rawDescData []byte
)

func file_whisper_proto_rawDescGZIP() []byte {
	file_whisper_proto_rawDescOnce.Do(func() {
		file_whisper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whisper_proto_rawDesc), len(file_whisper_proto_rawDesc)))
	})
	return file_whisper_proto_rawDescData
}

var file_whisper_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_whisper_proto_goTypes = []any{
	(*TranscribeRequest)(nil),             // 0: whisper.TranscribeRequest
	(*TranscribeResponse)(nil),            // 1: whisper.TranscribeResponse
	(*GetJobStatusRequest)(nil),           // 2: whisper.GetJobStatusRequest
	(*JobStatusResponse)(nil),             // 3: whisper.JobStatusResponse
	(*CreateUploadSessionRequest)(nil),    // 4: whisper.CreateUploadSessionRequest
	(*UploadSessionResponse)(nil),         // 5: whisper.UploadSessionResponse
	(*UploadChunkRequest)(nil),            // 6: whisper.UploadChunkRequest
	(*UploadChunkResponse)(nil),           // 7: whisper.UploadChunkResponse
	(*GetUploadSessionStatusRequest)(nil), // 8: whisper.GetUploadSessionStatusRequest
	(*FinalizeUploadSessionRequest)(nil),  // 9: whisper.FinalizeUploadSessionRequest
	(*FinalizeUploadSessionResponse)(nil), // 10: whisper.FinalizeUploadSessionResponse
}
var file_whisper_proto_depIdxs = []int32{
	0,  // 0: whisper.WhisperService.Transcribe:input_type -> whisper.TranscribeRequest
	2,  // 1: whisper.WhisperService.GetJobStatus:input_type -> whisper.GetJobStatusRequest
	4,  // 2: whisper.WhisperService.CreateUploadSession:input_type -> whisper.CreateUploadSessionRequest
	6,  // 3: whisper.WhisperService.UploadChunk:input_type -> whisper.UploadChunkRequest
	8,  // 4: whisper.WhisperService.GetUploadSessionStatus:input_type -> whisper.GetUploadSessionStatusRequest
	9,  // 5: whisper.WhisperService.FinalizeUploadSession:input_type -> whisper.FinalizeUploadSessionRequest
	1,  // 6: whisper.WhisperService.Transcribe:output_type -> whisper.TranscribeResponse
	3,  // 7: whisper.WhisperService.GetJobStatus:output_type -> whisper.JobStatusResponse
	5,  // 8: whisper.WhisperService.CreateUploadSession:output_type -> whisper.UploadSessionResponse
	7,  // 9: whisper.WhisperService.UploadChunk:output_type -> whisper.UploadChunkResponse
	5,  // 10: whisper.WhisperService.GetUploadSessionStatus:output_type -> whisper.UploadSessionResponse
	10, // 11: whisper.WhisperService.FinalizeUploadSession:output_type -> whisper.FinalizeUploadSessionResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_whisper_proto_init() }
func file_whisper_proto_init() {
	if File_whisper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whisper_proto_rawDesc), len(file_whisper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whisper_proto_goTypes,
		DependencyIndexes: file_whisper_proto_depIdxs,
		MessageInfos:      file_whisper_proto_msgTypes,
	}.Build()
	File_whisper_proto = out.File
	file_whisper_proto_goTypes = nil
	file_whisper_proto_depIdxs = nil
}
