package services

import (
	"os"
	"strings"
	"testing"
	"text/template"
)

// TestSummaryPDFRenderer_MeetingInfoExcludesContext verifies that the
// meeting-information section in the PDF template does not render the
// agenda/context row. This is a template-level assertion to ensure the
// presentation layer correctly excludes context from the metadata table.
func TestSummaryPDFRenderer_MeetingInfoExcludesContext(t *testing.T) {
	// Create template data similar to what the renderer would produce
	data := templateData{
		SummaryPDFMeta: SummaryPDFMeta{
			Language:     "English",
			Context:      "Test agenda context that should not appear",
			Date:         "2026-03-16",
			Location:     "Test Location",
			Participants: "Test Participants",
			CompanyName:  "Test Company",
		},
		SummaryHTML:        "<p>Test summary</p>",
		LogoDataURI:        "",
		LblMeetingInfo:     "Meeting Information",
		LblDate:            "Date",
		LblLocation:        "Location",
		LblRoom:            "Room",
		LblParticipants:    "Participants",
		LblFooterRights:    "All rights reserved.",
		LblFooterGenerated: "This document was automatically generated.",
	}

	// Read the template file
	tmplPath := "../../../../assets/templates/pdf/mom_main.html"
	tmplContent, err := os.ReadFile(tmplPath)
	if err != nil {
		t.Fatalf("Failed to read template file: %v", err)
	}

	// Parse the template
	tmpl, err := template.New("mom_main.html").Parse(string(tmplContent))
	if err != nil {
		t.Fatalf("Failed to parse template: %v", err)
	}

	// Execute the template
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		t.Fatalf("Failed to execute template: %v", err)
	}

	renderedHTML := buf.String()

	// Verify that the meeting information section does NOT contain context-related labels
	contextLabels := []string{
		"Agenda Context",
		"Konteks Agenda",
		"LblContext",
	}

	for _, label := range contextLabels {
		if strings.Contains(renderedHTML, label) {
			t.Errorf("Meeting information section should not contain context label %q, but it was found in rendered HTML", label)
		}
	}

	// Verify that the context value is NOT rendered in the table
	if strings.Contains(renderedHTML, "Test agenda context that should not appear") {
		t.Error("Meeting information section should not render the context value")
	}

	// Verify that expected fields ARE present
	expectedFields := []string{
		"Date",
		"Location",
		"Participants",
		"2026-03-16",
		"Test Location",
		"Test Participants",
	}

	for _, field := range expectedFields {
		if !strings.Contains(renderedHTML, field) {
			t.Errorf("Meeting information section should contain %q, but it was not found", field)
		}
	}
}

// TestSummaryPDFRenderer_TemplateDataStructure verifies that the templateData
// struct does not include the LblContext field anymore.
func TestSummaryPDFRenderer_TemplateDataStructure(t *testing.T) {
	// This test ensures the templateData struct is correctly defined
	// without the LblContext field.
	data := templateData{
		SummaryPDFMeta: SummaryPDFMeta{
			Language: "English",
		},
		LblMeetingInfo:     "Meeting Information",
		LblDate:            "Date",
		LblLocation:        "Location",
		LblRoom:            "Room",
		LblParticipants:    "Participants",
		LblFooterRights:    "All rights reserved.",
		LblFooterGenerated: "Generated by AI",
	}

	// Verify that the struct can be created without LblContext
	// If LblContext was still in the struct, this test would need to set it
	// The fact that we can create it without LblContext proves it's removed
	if data.LblMeetingInfo != "Meeting Information" {
		t.Error("LblMeetingInfo should be set correctly")
	}
}
